#pragma once
#include "config_common.h"

#undef LOCKING_SUPPORT_ENABLE
#undef LOCKING_RESYNC_ENABLE

#define NO_MUSIC_MODE
#define NO_ACTION_MACRO
#define NO_ACTION_FUNCTION
#define LAYER_STATE_16BIT

#define ONESHOT_TIMEOUT 1000
#define CAPS_WORD_IDLE_TIMEOUT 2500

#define TAPPING_TERM 200
#define TAPPING_TERM_PER_KEY
#define IGNORE_MOD_TAP_INTERRUPT
#define PERMISSIVE_HOLD
