#pragma once

#undef LOCKING_SUPPORT_ENABLE
#undef LOCKING_RESYNC_ENABLE

#define NO_MUSIC_MODE
#define NO_ACTION_MACRO
#define NO_ACTION_FUNCTION
#define LAYER_STATE_16BIT

#define ONESHOT_TIMEOUT 1000

#define TAPPING_TERM 200
#define TAPPING_TERM_PER_KEY
#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD
#define PERMISSIVE_HOLD
